# Generated by Django 4.0.6 on 2023-03-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('num', models.IntegerField(max_length=255)),
                ('date', models.DateTimeField(max_length=255)),
                ('time', models.DateTimeField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('num', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=255)),
            ],
        ),
    ]
