# Generated by Django 4.0.6 on 2023-03-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltaire', '0002_appointment_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num',
            field=models.IntegerField(),
        ),
    ]
