# Generated by Django 4.0.6 on 2023-03-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltaire', '0003_alter_appointment_date_alter_appointment_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
