# Generated by Django 4.0.6 on 2023-03-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltaire', '0006_alter_appointment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='num',
            new_name='number',
        ),
    ]
