# Generated by Django 4.0.6 on 2023-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltaire', '0007_rename_first_name_contact_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
